version: '3.0'
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  mongo:
    container_name: mongo-container
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 8081:8081
networks:
  es-net:
    driver: bridge
